def get_html_template(title, content):
    css_style = "body { font-family: sans-serif; max-width: 800px; margin: 2em auto; } nav { background: #333; padding: 1em; } nav a { color: white; padding: 1em; } footer { text-align: center; margin-top: 2em; }"
    nav_bar = """
    <nav>
        <a style="color: red;" href="./index.html">Home</a>
        <a style="color: green;"href="./about.html">About</a>
    </nav>
    """
    return f'<!DOCTYPE html><html><head><title>{title}</title><style>{css_style}</style></head><body>{nav_bar}<main>{content}</main><footer style="color: yellow;">Generated by MarkdownPress</footer></body></html>'